# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stefano
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I share my findings here. At least the ones that I think are useful for someone just starting finding bugs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://esevece.github.io" # the base hostname & protocol for your site
twitter_username: esevece
hackerone_username: esevece
# github_username:  jekyll

# Build settings
markdown: kramdown
